# permissions for end users to view keycloaks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: keycloak-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: px-client-operator
    app.kubernetes.io/part-of: px-client-operator
    app.kubernetes.io/managed-by: kustomize
  name: keycloak-viewer-role
rules:
- apiGroups:
  - cache.calvarado04.com
  resources:
  - keycloaks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.calvarado04.com
  resources:
  - keycloaks/status
  verbs:
  - get
