---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - persistentvolumeclaims
  - pods
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pxclient.calvarado04.com
  resources:
  - brokers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pxclient.calvarado04.com
  resources:
  - brokers/finalizers
  verbs:
  - update
- apiGroups:
  - pxclient.calvarado04.com
  resources:
  - brokers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - pxclient.calvarado04.com
  resources:
  - frontends
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pxclient.calvarado04.com
  resources:
  - frontends/finalizers
  verbs:
  - update
- apiGroups:
  - pxclient.calvarado04.com
  resources:
  - frontends/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - pxclient.calvarado04.com
  resources:
  - keycloaks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pxclient.calvarado04.com
  resources:
  - keycloaks/finalizers
  verbs:
  - update
- apiGroups:
  - pxclient.calvarado04.com
  resources:
  - keycloaks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - pxclient.calvarado04.com
  resources:
  - postgres
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pxclient.calvarado04.com
  resources:
  - postgres/finalizers
  verbs:
  - update
- apiGroups:
  - pxclient.calvarado04.com
  resources:
  - postgres/status
  verbs:
  - get
  - patch
  - update
