apiVersion: pxclient.calvarado04.com/v1alpha1
kind: Postgres
metadata:
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/part-of: px-client-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: px-client-operator
  name: postgres
spec:
  size: 1
  containerPort: 5432
  storageClassName: px-csi-db
  storageSize: 5Gi
  postgresDatabase: keycloak
  postgresUser: postgres
  postgresPassword: postgres
  containerImage: "postgres:16"