---
# add portworxToken from secret px-admin-token present in the namespace where Portworx was installed
apiVersion: pxclient.calvarado04.com/v1alpha1
kind: Broker
metadata:
  labels:
    app.kubernetes.io/name: broker
    app.kubernetes.io/instance: broker
    app.kubernetes.io/part-of: px-client-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: px-client-operator
  name: broker
spec:
  size: 1
  containerImage: "calvarado2004/portworx-client-broker:latest"
  portworxNamespace: "portworx"
---
apiVersion: v1
kind: Secret
metadata:
  name: portworx-token
type: Opaque
data:
  token: ""
---